DashboardATM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('select2/', include('django_select2.urls')),
    path('chaining/', include('smart_selects.urls')),
    path('', include('dashboard.urls')),
    path('', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('location/', include('locations.urls')),
    path('atm/', include('atms.urls')),
    path('event/', include('events.urls')),
    path('fees/', include('fees.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

atms/urls.py
from django.urls import path
from atms import views

urlpatterns = [
    path('', views.Index.as_view(), name='atm-home'),
    path('create/',views.ATMCreateView.as_view(), name='atm-create'),
    path('read/<int:pk>', views.ATMReadView.as_view(), name='atm-read'),
    path('update/<int:pk>', views.ATMUpdateView.as_view(), name='atm-update'),
    path('delete/<int:pk>', views.ATMDeleteView.as_view(), name='atm-delete'),
]

atms/models.py
from django.db import models
from locations.models import Location

# Create your models here.
class ATM(models.Model):
    name = models.CharField(max_length=200)
    name_vynamic = models.CharField(max_length=100, blank=True, null=True)
    name_way4 = models.CharField(max_length=200, blank=True, null=True)
    terminal_id = models.CharField(max_length=20, blank=True, null=True)
    machine_no = models.CharField(max_length=20, blank=True, null=True)
    gateway = models.CharField(max_length=30, blank=True, null=True)
    ip = models.CharField(max_length=30, blank=True, null=True)
    camera_ip = models.CharField(max_length=30, blank=True, null=True)
    date_setup = models.DateTimeField(null=True, blank=True)
    date_operate = models.DateTimeField(null=True, blank=True)
    date_deactivated = models.DateTimeField(null=True, blank=True)
    ghost_vesion = models.CharField(max_length=30, blank=True, null=True)
    soft_choice = (
        ('ts', 'Terminal Security'),
        ('s', 'Symantec'),
    )
    security_soft = models.CharField(max_length=20, choices=soft_choice, blank=True, null=True)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    status_choice = (
        ('hd', 'Hoạt Động'),
        ('nhd', 'Ngưng Hoạt Động'),
        ('ld', 'Lắp Đặt'),
    )
    status = models.CharField(max_length=20, choices=status_choice, default='hd')

    

    def __str__(self):
        return self.name
    

atms/forms.py
from django import forms
from bootstrap_modal_forms.forms import BSModalForm, BSModalModelForm
from atms.models import ATM

class ATMForm(BSModalModelForm):

    class Meta:
        model = ATM
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tên ATM/CDM'}),
            'name_vynamic': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tên Vynamic View'}),
            'name_way4': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Tên WAY4'}),
            'terminal_id': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Terminal ID'}),
            'machine_no': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Machine NO'}),
            'gateway': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Gateway'}),
            'ip': forms.TextInput(attrs={'class': 'form-control','placeholder': 'IP ATM'}),
            'camera_ip': forms.TextInput(attrs={'class': 'form-control','placeholder': 'IP Camera'}),
            'date_setup': forms.DateTimeInput(format='%m/%d/%Y', attrs={'class': 'form-control datepicker','placeholder': 'Ngày Lắp Đặt'}),
            'date_operate': forms.DateTimeInput(format='%m/%d/%Y', attrs={'class':'form-control datepicker', 'placeholder': 'Ngày Vận Hành'}),
            'date_deactivated': forms.DateTimeInput(format='%m/%d/%Y', attrs={'class':'form-control datepicker', 'placeholder': 'Ngày Ngưng Hoạt Động'}),
            'ghost_vesion': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Phiên Bản Ghost'}),
            'security_soft': forms.Select(attrs={'class': 'form-control selectpicker', 'data-style': 'btn btn-rose btn-sm', 'placeholder': 'Phần Mềm Bảo Mật'}),
            'status': forms.Select(attrs={'class': 'form-control selectpicker', 'data-style': 'btn btn-rose btn-sm', 'placeholder': 'Trạng Thái'}),
            

        }


atms/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q

from bootstrap_modal_forms.generic import (
    BSModalCreateView,
    BSModalDeleteView,
    BSModalFormView,
    BSModalReadView,
    BSModalUpdateView,
)

from atms.models import ATM
from locations.models import Location
from atms.forms import ATMForm

# Create your views here.
@method_decorator(login_required, name='dispatch')
class Index(generic.ListView):
    model = ATM
    context_object_name = 'atms'
    template_name = 'atm_home.html'

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        atms = ATM.objects.all()

        context['total_atms'] = atms.filter(status='hd').count()
        context['total_atm'] = atms.filter(name__contains='atm').count()
        context['total_cdm'] = atms.filter(name__contains='cdm').count()
        return context
    
@method_decorator(login_required, name='dispatch')
class ATMCreateView(BSModalCreateView):
    template_name = 'atm_create.html'
    form_class = ATMForm
    success_message = 'Thành công: Một ATM mới đã được khởi tạo!'
    success_url = reverse_lazy('atm-home')

@method_decorator(login_required, name='dispatch')
class ATMReadView(BSModalReadView):
    model = ATM
    template_name = 'atm_read.html'

@method_decorator(login_required, name='dispatch')
class ATMUpdateView(BSModalUpdateView) :
    model = ATM
    form_class = ATMForm
    template_name = 'atm_update.html'
    success_message = 'Thành công: ATM đã được cập nhật!'
    success_url = reverse_lazy('atm-home')

@method_decorator(login_required, name='dispatch')
class ATMDeleteView(BSModalDeleteView):
    model = ATM
    template_name = 'atm_delete.html'
    success_message = 'Thành công: ATM đã được xóa hoàn toàn!'
    success_url = reverse_lazy('atm-home')

atms/templates/atm_delete.html
<form method="post" action="">
    {% csrf_token %}
    <div class="modal-body">
        <div class="info text-center">
            <div class="icon icon-danger ">
                <i class="material-icons">delete_forever</i>
            </div>
            <h2 class="info-title text-danger">BẠN CÓ CHẮC CHẮN MUỐN XOÁ?</h2>
            <p>Xoá toàn bộ thông tin về điểm <span class="text-primary">{{ atm.name }}</span>!</p>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-danger">Xoá</button>
        <button type="submit" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
    </div>

</form>

atms/templates/atm_home.html
{% extends 'layouts/base.html' %}

{% block title %}
    Thông Tin ATM/CDM
{% endblock title %}

{% block stylesheets %}
<style>
  .title-atms {
    font-size: 20px;
    font-weight: 700;
  }
  .select2-selection__rendered {
    font-size: 14px;
  }
  .alert-atm {
      display: inline-block;
      margin: 15px auto;
      position: fixed;
      transition: all 0.5s ease-in-out 0s;
      z-index: 1031;
      top: 20px;
      right: 20px;
  }
</style>
{% endblock stylesheets %}

{% block content %}    
  <div>
      {% if messages %}
          {% for message in messages %}
              <div class="col-11 col-md-4 alert alert-success alert-with-icon alert-atm" data-notify="container">
                  <i class="material-icons" data-notify="icon">notifications</i>
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <i class="material-icons">close</i>
                  </button>
                  <span data-notify="icon" class="now-ui-icons ui-1_bell-53"></span>
                  <span data-notify="message">{{ message }}</span>
              </div>
          {% endfor %}            
      {% endif %}
  </div>
  <div class="modal fade" id="create-modal"  role="dialog" aria-hidden="true">
      <div class="modal-dialog modal-lg">
          <div class="modal-content">
          </div>
      </div>
      </div>

      <div class="modal fade"  role="dialog" id="modal">
      <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content"></div>
      </div>
  </div>
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-6">
          <div class="card card-stats">
            <div class="card-header card-header-primary card-header-icon">
              <div class="card-icon">
                <i class="material-icons">my_location</i>
              </div>
              <p class="card-category">Tổng Số ATM/CDM</p>
              <h3 class="card-title">{{ total_atms }}</h3>
            </div>
            <div class="card-footer">
              <div class="stats">
                <i class="material-icons">healing</i> Có mặt trên khắp cả nước
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
          <div class="card card-stats">
            <div class="card-header card-header-info card-header-icon">
              <div class="card-icon">
                <i class="material-icons">nature</i>
              </div>
              <p class="card-category">Tổng Số ATM</p>
              <h3 class="card-title">{{ total_atm }}</h3>
            </div>
            <div class="card-footer">
              <div class="stats">
                <i class="material-icons">filter_vintage</i> Các máy rút tiền
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
          <div class="card card-stats">
            <div class="card-header card-header-success card-header-icon">
              <div class="card-icon">
                <i class="material-icons">nature_people</i>
              </div>
              <p class="card-category">Tổng Số CDM</p>
              <h3 class="card-title">{{ total_cdm }}</h3>
            </div>
            <div class="card-footer">
              <div class="stats">
                <i class="material-icons">flare</i> Các máy nộp tiền tự động
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
          <div class="card card-stats">
            <div class="card-header card-header-warning card-header-icon">
              <div class="card-icon">
                <i class="fa fa-twitter"></i>
              </div>
              <p class="card-category">Tổng ...</p>
              <h3 class="card-title"></h3>
            </div>
            <div class="card-footer">
              <div class="stats">
                <i class="material-icons">warning</i> Khu vực trọng điểm
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-primary card-header-icon">
                <div class="card-icon">
                    <i class="material-icons">assignment</i>
                </div>
                <h4 class="card-title">THÔNG TIN ATM/CDM</h4>
            </div>
            <div class="card-body">
              <div class="toolbar">
                  <button id="atm-create" class="bs-modal btn btn-primary" type="button" name="button" data-form-url="{% url 'atm-create' %}">
                      <i class="material-icons">add_box</i> Thêm ATM/CDM
                  </button>
              </div>
              <div class="material-datatables">
                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                  <thead>                                        
                    <tr>
                      <th>#</th>
                      <th>Tên ATM</th>                         
                      <th>Gateway</th>
                      <th>IP</th>
                      <th>Camera IP</th>
                      <th>Điện Thoại</th>
                      <th>Tỉnh/Thành Phố</th>
                      <th>Vị Trí</th>                                             
                      <th class="text-right disabled-sorting">Action</th>
                    </tr>
                  </thead>
                    <tfoot>
                      <tr>
                        <th>STT</th>
                        <th>Tên ATM</th>                          
                        <th>Gateway</th>
                        <th>IP</th>
                        <th>Camera IP</th>
                        <th>Điện Thoại</th>
                        <th>Tỉnh/Thành Phố</th>
                        <th>Vị Trí</th>   
                        <th class="text-right">Action</th>
                      </tr>
                    </tfoot>
                    <tbody>
                      {% for atm in atms %}
                        <tr>
                          <th>{{ forloop.counter }}</th>
                          <td class="text-primary">{{ atm.name }}</td>  
                          <td>{{ atm.gateway }}</td>
                          <td>{{ atm.ip }}</td>
                          <td>{{ atm.camera_ip }}</td>
                          <td>{{ atm.location.contact01 }}</td>
                          <td>{{ atm.location.city }}</td>
                          <td>{{ atm.location.get_area_display }}</td>
                          <td class="text-right ">
                            <button type="button" class="bs-modal btn btn-sm btn-info btn-just-icon btn-link" data-form-url="{% url 'atm-read' atm.pk %}">
                              <i class="material-icons">visibility</i>
                            </button>
                            <button type="button" class="bs-modal btn btn-sm btn-warning btn-just-icon btn-link" data-form-url="{% url 'atm-update' atm.pk %}">
                              <i class="material-icons">create</i>
                            </button>
                            <button type="button" class="bs-modal btn btn-sm btn-danger btn-just-icon btn-link" data-form-url="{% url 'atm-delete' atm.pk %}">
                              <i class="material-icons">close</i>
                            </button>
                          </td>
                        </tr>
                      {% empty %}
                        <tr>
                          <td colspan="4">Chưa có thông tin! <a href="#">Tạo thông tin ATM ngay!</a>.</td>
                        </tr>
                      {% endfor %}
                    </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>        
    
{% endblock content %}

{% block javascripts %}
<script>
  $(document).ready(function() {
    $('#datatables').DataTable({
      "pagingType": "full_numbers",
      "lengthMenu": [
      [10, 25, 50, -1],
      [10, 25, 50, "All"]
      ],
      responsive: true,
      search: {
        smart: true
      },
      language: {
        search: "TÌM KIẾM: ",
        searchPlaceholder: "Thông Tin ATM...",
      }
    });
    var table = $('#datatable').DataTable();
  });

  //Hàm tự động render modal cho class bs-modal
  $(".bs-modal").each(function () {
      $(this).modalForm({formURL: $(this).data("form-url")});
  });  
  
  //Ẩn thông báo khi tạo mới, cập nhật hoặc xoá
  $(".alert").fadeTo(5000, 500).slideUp(500, function () {
      $(".alert").slideUp(500);
  
  }); 

  $('#modal').on('shown.bs.modal', function () {
    //Chèn select2 vào
    $('#id_location').select2({
      width: '100%',
      placeholder: "Chọn điểm ATM/CDM",
    });

    //Chèn Selectpicker vào
    $('.selectpicker').selectpicker();

    //Chèn datepicker vào (Nếu muốn chèn thêm time: datetimepicker )
    md.initFormExtendedDatetimepickers();
    

    //Focus vào ô đầu tiên
    setTimeout(function (){
      $('#id_name').focus();
    }, 500);

    atm_plug.initMaterialWizard();
    
    //Tự động mở drop khi nhấn tab
    $(document).on('focus', '.select2.select2-container', function (e) {
      var isOriginalEvent = e.originalEvent // don't re-open on closing focus event
      var isSingleSelect = $(this).find(".select2-selection--single").length > 0 // multi-select will pass focus to input

      if (isOriginalEvent && isSingleSelect) {
          $(this).siblings('select:enabled').select2('open');
      } 
    }); 
  }); 
</script>  
{% endblock javascripts %}



atms/templates/atm_read.html
<div class="modal-header">
    <h5 class="modal-title text-rose text-uppercase title-atms">{{ atm.name }}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-7">
            <div class="card">
                <div class="card-header card-header-icon card-header-rose">
                    <div class="card-icon">
                        <i class="material-icons">language</i>
                    </div>
                    <h4 class="card-title">Thông tin chung</h4>
                </div>
                <div class="card-body">
                    <p><span class="text-info h6 card-category"><i class="material-icons">shutter_speed</i> Tên VynamicView:</span>  {{ atm.name_vynamic }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">filter_vintage</i> Tên WAY4:</span> {{ atm.name_way4 }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">coronavirus</i> Terminal ID:</span>  {{ atm.terminal_id }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">api</i> Machine NO:</span>   {{ atm.machine_no }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">layers</i> Số Lượng ATM/CDM:</span>  {{ atm.location.number }}</p>                    
                    <p><span class="text-info h6 card-category"><i class="material-icons">flutter_dash</i> Ghost Version:</span>  {{ atm.ghost_vesion }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">privacy_tip</i> Security Version:</span>  {{ atm.get_security_soft_display }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">support</i> Trạng Thái:</span>  {{ atm.get_status_display }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="card">
                <div class="card-header card-header-icon card-header-rose">
                    <div class="card-icon">
                        <i class="material-icons">language</i>
                    </div>
                    <h4 class="card-title">Network & Setup</h4>
                </div>
                <div class="card-body">
                    <p><span class="text-info h6 card-category"><i class="material-icons">signal_cellular_alt</i> Gateway:</span>  {{ atm.gateway }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">storage</i> ATM IP:</span>  {{ atm.ip }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">photo_camera</i> Camera IP:</span>  {{ atm.camera_ip }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">book_online</i> Ngày Lắp Đặt:</span>  {{ atm.date_setup|date:"d/m/Y" }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">fact_check</i> Ngày Vận Hành:</span>  {{ atm.date_operate|date:"d/m/Y" }}</p> 
                    <p><span class="text-info h6 card-category"><i class="material-icons">settings_input_composite</i> Ngày Ngưng HĐ:</span>  {{ atm.date_deactivated|date:"d/m/Y" }}</p>                    
                    <p><span class="text-info h6 card-category"><i class="material-icons">room_preferences</i> Kiểu Lắp Đặt:</span>  {{ atm.location.get_setup_display }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">pin_drop</i> Vị Trí Đặt:</span>  {{ atm.location.get_area_display }}</p>                    
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-icon card-header-rose">
                    <div class="card-icon">
                        <i class="material-icons">language</i>
                    </div>
                    <h4 class="card-title">Liên Hệ</h4>
                </div>
                <div class="card-body">
                    <p><span class="text-info h6 card-category"><i class="material-icons">location_on</i> Địa Chỉ:</span>  {{ atm.location.street }}, {{ atm.location.ward }}, {{ atm.location.district }}, {{ atm.location.city }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">apartment</i> Đơn Vị Quản Lý:</span> {{ atm.location.manager }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">support_agent</i> Liên Hệ 01:</span> {{ atm.location.contact01 }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">contact_phone</i> Liên Hệ 02:</span> {{ atm.location.contact02 }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">stay_primary_portrait</i> Liên Hệ 03:</span> {{ atm.location.contact03 }}</p>
                    <p><span class="text-info h6 card-category"><i class="material-icons">stay_primary_portrait</i> Liên Hệ 04:</span> {{ atm.location.contact04 }}</p>
                    
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>