DashboardATM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('select2/', include('django_select2.urls')),
    path('chaining/', include('smart_selects.urls')),
    path('', include('dashboard.urls')),
    path('', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('location/', include('locations.urls')),
    path('atm/', include('atms.urls')),
    path('event/', include('events.urls')),
    path('fees/', include('fees.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

atms/urls.py
from django.urls import path
from atms import views

urlpatterns = [
    path('', views.Index.as_view(), name='atm-home'),
    path('create/',views.ATMCreateView.as_view(), name='atm-create'),
    path('read/<int:pk>', views.ATMReadView.as_view(), name='atm-read'),
    path('update/<int:pk>', views.ATMUpdateView.as_view(), name='atm-update'),
    path('delete/<int:pk>', views.ATMDeleteView.as_view(), name='atm-delete'),
]

locations/urls.py
from django.urls import path
from locations import views

urlpatterns = [
    path('', views.Index.as_view(), name='location-home'),
    path('create/',views.LocationCreateView.as_view(), name='location-create'),
    path('read/<int:pk>', views.LocationReadView.as_view(), name='location-read'),
    path('update/<int:pk>', views.LocationUpdateView.as_view(), name='location-update'),
    path('delete/<int:pk>', views.LocationDeleteView.as_view(), name='location-delete'),
]

locations/models.py
from django.db import models
from smart_selects.db_fields import ChainedForeignKey
from django.urls import reverse

# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class District(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Ward(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Manager(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Location(models.Model):
    name = models.CharField(max_length=100)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    district = ChainedForeignKey(
        'District',
        chained_field='city',
        chained_model_field='city',
        show_all=False,
        auto_choose=True,
        
    )
    ward = ChainedForeignKey(
        'Ward',
        chained_field='district',
        chained_model_field='district',
        show_all=False,
        auto_choose=True,
        
    )
    street = models.CharField(max_length=200)
    manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    number = models.IntegerField(blank=True, null=True)
    setup_choice = (
        ('xp', 'XP'),
        ('xt', 'XT'),
        ('s', 'S'),
    )
    setup = models.CharField(max_length=10, choices=setup_choice)
    area_choice = (
        ('in', 'Điểm Trong ACB'),
        ('out', 'Điểm Ngoài ACB'),
    )
    area = models.CharField(max_length=20, choices=area_choice)
    contact01 = models.CharField(max_length=100, blank=True, null=True)
    contact02 = models.CharField(max_length=100, blank=True, null=True)
    contact03 = models.CharField(max_length=100, blank=True, null=True)
    contact04 = models.CharField(max_length=100, blank=True, null=True)
    status_choice = (
        ('nhd', 'Ngưng Hoạt Động'),
        ('hd', 'Hoạt Động'),
    )
    status = models.CharField(max_length=20, choices=status_choice, default='hd', blank=True
    , null=True)

    def __str__(self):
        return self.name

    

    
    
    
    

locations/forms.py
from django import forms
from bootstrap_modal_forms.forms import BSModalForm, BSModalModelForm
from django_select2.forms import Select2Widget
from locations.models import Location

class LocationForm(BSModalModelForm):
    
          
    class Meta:
        model = Location
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'street': forms.TextInput(attrs={'class': 'form-control'}),
            'number': forms.NumberInput(attrs={'class': 'form-control'}),
            'setup': forms.Select(attrs={'class': 'form-control selectpicker', 'data-style': 'btn btn-info btn-sm'}),
            'area': forms.Select(attrs={'class': 'form-control selectpicker', 'data-style': 'btn btn-info btn-sm'}),
            'contact01': forms.TextInput(attrs={'class': 'form-control'}),
            'contact02': forms.TextInput(attrs={'class': 'form-control'}),
            'contact03': forms.TextInput(attrs={'class': 'form-control'}),
            'contact04': forms.TextInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control selectpicker', 'data-style': 'btn btn-info btn-sm'}),
        }
        
       
    
    

locations/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Count

from bootstrap_modal_forms.generic import (
    BSModalCreateView,
    BSModalDeleteView,
    BSModalFormView,
    BSModalReadView,
    BSModalUpdateView,
)

from locations.forms import LocationForm
from locations.models import Location, City

# Create your views here.
@method_decorator(login_required, name='dispatch')
class Index(generic.ListView):
    model = Location
    context_object_name = 'locations'
    template_name = 'location_home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        locations = Location.objects.all()

        context['total_locations'] = locations.filter(status='hd').count()
        context['total_in'] = locations.filter(area = 'in').count()
        context['total_out'] = locations.filter(area='out').count()
        context['total_tp'] = locations.filter(city='79').count()
        return context
    


@method_decorator(login_required, name='dispatch')
class LocationCreateView(BSModalCreateView):
    template_name = 'location_create.html'
    form_class = LocationForm
    success_message = 'Tạo Điểm Lắp Đặt thành công!'
    success_url = reverse_lazy('location-home')

@method_decorator(login_required, name='dispatch')
class LocationReadView(BSModalReadView):
    model = Location
    template_name = 'location_read.html'

@method_decorator(login_required, name='dispatch')
class LocationUpdateView(BSModalUpdateView):
    model = Location
    template_name = 'location_update.html'
    form_class = LocationForm
    success_message = 'Cập nhật thành công!'
    success_url = reverse_lazy('location-home')

@method_decorator(login_required, name='dispatch')
class LocationDeleteView(BSModalDeleteView):
    model = Location
    template_name = 'location_delete.html'
    success_url = reverse_lazy('location-home')
    success_message = 'Đã xoá thành công!'

locations/templates/location_create.html
<form method="post" action="">
  {% csrf_token %}
  
  {{ form.media.js }}
  <div class="modal-header">
    <h5 class="modal-title">TẠO ĐIỂM LẮP ĐẶT</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="card ">
      <div class="card-header card-header-rose card-header-icon">
        <div class="card-icon">
          <i class="material-icons">contacts</i>
        </div>
      </div>
      <div class="card-body ">
        <div class="row">
          <label class="col-md-2 col-form-label">Tên Điểm</label>
          <div class="col-md-10">
            <div class="form-group has-default">
              {{ form.name }}
            </div>
          </div>
        </div>
        <div class="row">
          <label class="col-md-2 col-form-label">Tỉnh/Thành Phố</label>
          <div class="col-md-4">
            <div class="form-group">
              {{ form.city }}
            </div>
          </div>
          <label class="col-md-2 col-form-label">Huyện/Quận</label>
          <div class="col-md-4">
            <div class="form-group">
              {{ form.district }}
            </div>
          </div>
        </div>
        <div class="row">
          <label class="col-md-2 col-form-label">Xã/Phường</label>
          <div class="col-md-4">
            <div class="form-group">
              {{ form.ward }}
            </div>
          </div>
          <label class="col-md-2 col-form-label">Tên Đường</label>
          <div class="col-md-4">
            <div class="form-group">
              {{ form.street }}
            </div>
          </div>
        </div>
        <div class="row">
          <label class="col-md-2 col-form-label">Đơn Vị Quản Lý</label>
          <div class="col-md-4">
            <div class="form-group has-default">
              {{ form.manager }}
            </div>
          </div>
          <label class="col-md-2 col-form-label">Số Máy</label>
          <div class="col-md-4">
            <div class="form-group has-default">
              {{ form.number }}
            </div>
          </div>
        </div>
        <div class="row">
          <label class="col-md-2 col-form-label">Kiểu Lắp Đặt</label>
          <div class="col-md-4">
            <div class="form-group has-default">
              {{ form.setup }}
            </div>
          </div>
          <label class="col-md-2 col-form-label">Vị Trí Lắp Đặt</label>
          <div class="col-md-4">
            <div class="form-group">
              {{ form.area }}
            </div>
          </div>
        </div>

        <div class="row">
          <label class="col-md-2 col-form-label">Số CN/PGD</label>
          <div class="col-md-4">
            <div class="form-group">
              {{ form.contact01 }}
            </div>
          </div>
          <label class="col-md-2 col-form-label">Số Bảo Vệ</label>
          <div class="col-md-4">
            <div class="form-group">
              {{ form.contact02 }}
            </div>
          </div>
        </div>

        <div class="row">
          <label class="col-md-2 col-form-label">Liên Hệ 01</label>
          <div class="col-md-4">
            <div class="form-group">
              {{ form.contact03 }}
            </div>
          </div>
          <label class="col-md-2 col-form-label">Liên Hệ 02</label>
          <div class="col-md-4">
            <div class="form-group">
              {{ form.contact04 }}
            </div>
          </div>
        </div>

        <div class="row">
          
          <label class="col-md-2 col-form-label">Trạng Thái</label>
          <div class="col-md-10">
            <div class="form-group">
              {{ form.status }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
          
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Save changes</button>
    <button type="submit" class="btn btn-secondary" data-dismiss="modal">Close</button>
  </div>
</form>




locations/templates/location_delete.html
<form method="post" action="">
    {% csrf_token %}
    <div class="modal-body">
        <div class="info text-center">
            <div class="icon icon-danger ">
                <i class="material-icons">delete_forever</i>
            </div>
            <h2 class="info-title text-danger">BẠN CÓ CHẮC CHẮN MUỐN XOÁ?</h2>
            <p>Xoá toàn bộ thông tin về điểm <span class="text-primary">{{ location.name }}</span>!</p>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-danger">Xoá</button>
        <button type="submit" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
    </div>

</form>

locations/templates/location_home.html
{% extends 'layouts/base.html' %}

{% block title %}
    Điểm Lắp Đặt ATM/CDM
{% endblock title %}

{% block stylesheets %}
    <style>
        .btn-atm {
            width: 100%;
        }
        .alert-atm {
            display: inline-block;
            margin: 15px auto;
            position: fixed;
            transition: all 0.5s ease-in-out 0s;
            z-index: 1031;
            top: 20px;
            right: 20px;
        }
    </style>
{% endblock stylesheets %}

{% block content %}    
    <div>
        {% if messages %}
            {% for message in messages %}
                <div class="col-11 col-md-4 alert alert-success alert-with-icon alert-atm" data-notify="container">
                    <i class="material-icons" data-notify="icon">notifications</i>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <i class="material-icons">close</i>
                    </button>
                    <span data-notify="icon" class="now-ui-icons ui-1_bell-53"></span>
                    <span data-notify="message">{{ message }}</span>
                </div>
            {% endfor %}            
        {% endif %}
    </div>
    <div class="modal fade" id="create-modal"  role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
            </div>
        </div>
        </div>

        <div class="modal fade"  role="dialog" id="modal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content"></div>
        </div>
    </div>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
              <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                  <div class="card-header card-header-primary card-header-icon">
                    <div class="card-icon">
                      <i class="material-icons">my_location</i>
                    </div>
                    <p class="card-category">Tổng Số Điểm Đặt</p>
                    <h3 class="card-title">{{ total_locations }}</h3>
                  </div>
                  <div class="card-footer">
                    <div class="stats">
                      <i class="material-icons">healing</i> Có mặt trên khắp cả nước
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                  <div class="card-header card-header-info card-header-icon">
                    <div class="card-icon">
                      <i class="material-icons">nature</i>
                    </div>
                    <p class="card-category">Tổng Điểm Trong</p>
                    <h3 class="card-title">{{ total_in }}</h3>
                  </div>
                  <div class="card-footer">
                    <div class="stats">
                      <i class="material-icons">filter_vintage</i> Các điểm thuộc CN/PGD
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                  <div class="card-header card-header-success card-header-icon">
                    <div class="card-icon">
                      <i class="material-icons">nature_people</i>
                    </div>
                    <p class="card-category">Tổng Điểm Ngoài</p>
                    <h3 class="card-title">{{ total_out }}</h3>
                  </div>
                  <div class="card-footer">
                    <div class="stats">
                      <i class="material-icons">flare</i> Các điểm nằm bên ngoài CN/PGD
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="card card-stats">
                  <div class="card-header card-header-warning card-header-icon">
                    <div class="card-icon">
                      <i class="fa fa-twitter"></i>
                    </div>
                    <p class="card-category">Tổng Điểm TP.HCM</p>
                    <h3 class="card-title">{{ total_tp }}</h3>
                  </div>
                  <div class="card-footer">
                    <div class="stats">
                      <i class="material-icons">warning</i> Khu vực trọng điểm
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary card-header-icon">
                            <div class="card-icon">
                                <i class="material-icons">assignment</i>
                            </div>
                            <h4 class="card-title">ĐIỂM LẮP ĐẶT ATM</h4>
                        </div>
                        <div class="card-body">
                            <div class="toolbar">
                                <!--        Here you can write extra buttons/actions for the toolbar              -->
                                <button id="location-create" class="bs-modal btn btn-primary" type="button" name="button" data-form-url="{% url 'location-create' %}">
                                    <i class="material-icons">add_box</i> Thêm Điểm Lắp Đặt
                                </button>
                            </div>
                            <div class="material-datatables">
                                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                                    <thead>                                        
                                        <tr>
                                            <th>#</th>
                                            <th>Tên Điểm</th>                
                                            <th>Địa Điểm</th>                        
                                            <th>Vị Trí</th>                                            
                                            <th class="text-right disabled-sorting">Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>STT</th>
                                            <th>Tên Điểm</th>
                                            <th>Địa Điểm</th>                                            
                                            <th>Vị Trí</th>  
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% for location in locations %}
                                            <tr>
                                                <th>{{ forloop.counter }}</th>
                                                <td class="text-primary">{{ location.name }}</td>                                                
                                                <td>{{ location.street }} - {{ location.ward.name }} - {{ location.district.name }} - {{ location.city.name }}</td>                                              
                                                <td>{{ location.get_area_display }}</td>
                                                <td class="text-right ">
                                                    <button type="button" class="bs-modal btn btn-sm btn-info btn-just-icon btn-link" data-form-url="{% url 'location-read' location.pk %}">
                                                        <i class="material-icons">visibility</i>
                                                    </button>
                                                    <button type="button" class="bs-modal btn btn-sm btn-warning btn-just-icon btn-link" data-form-url="{% url 'location-update' location.pk %}">
                                                        <i class="material-icons">create</i>
                                                    </button>
                                                    <button type="button" class="bs-modal btn btn-sm btn-danger btn-just-icon btn-link" data-form-url="{% url 'location-delete' location.pk %}">
                                                        <i class="material-icons">close</i>
                                                    </button>
                                                </td>
                                            </tr>
                                        {% empty %}
                                            <tr>
                                                <td colspan="4">Chưa có thông tin! <a href="#">Tạo điểm lắp đặt ngay!</a>.</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- end content-->
                    </div>
                    <!--  end card  -->
                </div>
                <!-- end col-md-12 -->
            </div>
            <!-- end row -->
        </div>
    </div>        
    
{% endblock content %}

{% block javascripts %}
<script>
  $(document).ready(function() {
    $('#datatables').DataTable({
      "pagingType": "full_numbers",
      "lengthMenu": [
        [10, 25, 50, -1],
        [10, 25, 50, "All"]
      ],
      responsive: true,
      language: {
        search: "",
        searchPlaceholder: "Tìm kiếm điểm lắp đặt",
      }
    });
    var table = $('#datatable').DataTable();
  });

  //Hàm tự động render modal cho class bs-modal
  $(".bs-modal").each(function () {
    $(this).modalForm({formURL: $(this).data("form-url")});
  });

  //Ẩn thông báo khi tạo mới, cập nhật hoặc xoá
  $(".alert").fadeTo(5000, 500).slideUp(500, function () {
      $(".alert").slideUp(500);
  
  }); 

  $('#modal').on('shown.bs.modal', function () {
    //Chèn select2 vào
    $('#id_city, #id_district, #id_ward, #id_manager').select2({
      width: '100%',
      placeholder: "Lựa chọn thông tin...",
    });

    //Chèn Selectpicker vào
    $('.selectpicker').selectpicker();

    //Focus vào ô đầu tiên
    setTimeout(function (){
      $('#id_name').focus();
    }, 500);

    //Tự động mở drop khi nhấn tab
    $(document).on('focus', '.select2.select2-container', function (e) {
      var isOriginalEvent = e.originalEvent // don't re-open on closing focus event
      var isSingleSelect = $(this).find(".select2-selection--single").length > 0 // multi-select will pass focus to input

      if (isOriginalEvent && isSingleSelect) {
        $(this).siblings('select:enabled').select2('open');
      } 
    });
  });  
</script>  
{% endblock javascripts %}



locations/templates/location_read.html
<div class="card card-signup card-plain">
    <div class="modal-header">
        <div class="card-header card-header-primary text-center">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                <i class="material-icons">clear</i>
            </button>
            <h4 class="card-title">{{ location.name }}</h4>
        </div>
    </div>
    <div class="modal-body">
        <form class="form" method="" action="">
            <p class="description text-center">Thông tin chi tiết về điểm lắp đặt</p>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <span class="btn btn-warning btn-atm text-left ">
                            <i class="material-icons">location_on</i> Địa Điểm
                        </span>
                    </div>
                    <div class="col-md-8">
                        <span class="btn btn-info">
                            {{ location.street }} - {{ location.ward.name }} - {{ location.district.name }} - {{ location.city.name }}
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <span class="btn btn-warning btn-atm text-left">
                            <i class="material-icons">apartment</i> Đơn Vị Quản Lý
                        </span>
                    </div>
                    <div class="col-md-8">
                        <span class="btn btn-info">
                            {{ location.manager.name }}
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <span class="btn btn-warning btn-atm text-left">
                            <i class="material-icons">layers</i> Số Lượng ATM/CDM
                        </span>
                    </div>
                    <div class="col-md-8">
                        <span class="btn btn-info">
                            {{ location.number }}
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <span class="btn btn-warning btn-atm text-left">
                            <i class="material-icons">room_preferences</i> Kiểu Lắp Đặt
                        </span>
                    </div>
                    <div class="col-md-8">
                        <span class="btn btn-info">
                            {{ location.get_setup_display }}
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <span class="btn btn-warning btn-atm text-left">
                            <i class="material-icons">pin_drop</i> Vị Trí Lắp Đặt
                        </span>
                    </div>
                    <div class="col-md-8">
                        <span class="btn btn-info">
                            {{ location.get_area_display }}
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <span class="btn btn-warning btn-atm text-left">
                            <i class="material-icons">support_agent</i> Số Điện Thoại CN/PGD
                        </span>
                    </div>
                    <div class="col-md-8">
                        <span class="btn btn-info">
                            {{ location.contact01 }}
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <span class="btn btn-warning btn-atm text-left">
                            <i class="material-icons">contact_phone</i> Số Điện Thoại Công Ty
                        </span>
                    </div>
                    <div class="col-md-8">
                        <span class="btn btn-info">
                            {{ location.contact02 }}
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <span class="btn btn-warning btn-atm text-left">
                            <i class="material-icons">stay_primary_portrait</i> Nhân Viên Tại Chỗ
                        </span>
                    </div>
                    <div class="col-md-8">
                        <span class="btn btn-info">
                            {{ location.contact03 }}
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <span class="btn btn-warning btn-atm text-left ">
                            <i class="material-icons">stay_primary_portrait</i> Nhân Viên Tại Chỗ
                        </span>
                    </div>
                    <div class="col-md-8">
                        <span class="btn btn-info">
                            {{ location.contact04 }}
                        </span>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer justify-content-center">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
    </div>
</div>