DashboardATM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('select2/', include('django_select2.urls')),
    path('chaining/', include('smart_selects.urls')),
    path('', include('dashboard.urls')),
    path('', include('users.urls')),
    path('blog/', include('blog.urls')),
    path('location/', include('locations.urls')),
    path('atm/', include('atms.urls')),
    path('event/', include('events.urls')),
    path('fees/', include('fees.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

atms/urls.py
from django.urls import path
from atms import views

urlpatterns = [
    path('', views.Index.as_view(), name='atm-home'),
    path('create/',views.ATMCreateView.as_view(), name='atm-create'),
    path('read/<int:pk>', views.ATMReadView.as_view(), name='atm-read'),
    path('update/<int:pk>', views.ATMUpdateView.as_view(), name='atm-update'),
    path('delete/<int:pk>', views.ATMDeleteView.as_view(), name='atm-delete'),
]

events/urls.py
from django.urls import path
from events import views

urlpatterns = [
    path('', views.Index.as_view(), name='event-home'),
    path('create/',views.EventCreateView.as_view(), name='event-create'),
    #path('read/<int:pk>', views.EventsUpdateView.as_view(), name='event-read'),
    path('update/<int:pk>', views.EventUpdateView.as_view(), name='event-update'),
    path('delete/<int:pk>', views.EventDeleteView.as_view(), name='event-delete'),
]

events/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from smart_selects.db_fields import ChainedForeignKey

from atms.models import ATM

# Create your models here.

class Department(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class CodeError(models.Model):
    name = models.CharField(max_length=100)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Error(models.Model):    
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    code_error = ChainedForeignKey(
        'CodeError',
        chained_field='department',
        chained_model_field='department',
        show_all=False,
        auto_choose=True,
    )
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class HandlingStaff(models.Model):
    handling_staff = models.CharField(max_length=80)

    def __str__(self):
        return self.handling_staff
    

class Event(models.Model):
    name = models.ForeignKey(ATM, on_delete=models.CASCADE)
    error = models.ForeignKey(Error, on_delete=models.CASCADE)
    status_choice = (
        ('new', 'Mới'),
        ('process', 'Đang Xử Lý'),
        ('complete', 'Hoàn Thành'),
        ('close', 'Kết Thúc'),
    )
    status = models.CharField(max_length=20, choices=status_choice, default='new')
    status_atm_choice = (
        ('in_services', 'In Services'),
        ('out_services', 'Out Of Services'),
        ('offline', 'Offline'),
    )
    status_atm = models.CharField(max_length=20, choices=status_atm_choice, default='out_services')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_create = models.DateTimeField(auto_now_add=True)
    date_complete = models.DateTimeField(blank=True, null=True)
    date_post = models.DateTimeField(blank=True, null=True)
    date_close = models.DateTimeField(blank=True, null=True)
    priority_choice = (
        ('low', 'Thấp'),
        ('medium', 'Bình Thường'),
        ('high', 'Cao')
    )
    priority = models.CharField(max_length=20, choices=priority_choice, default='medium')
    supervisor_note = models.TextField(blank=True, null=True)
    report24h = models.BooleanField(default=False)
    replace_components = models.BooleanField(default=False)
    end_funds = models.BooleanField(default=False)
    to_funds = models.BooleanField(default=False)
    handling_staff_event = models.ForeignKey(HandlingStaff, on_delete=models.CASCADE,  blank=True, null=True)

    
    def __str__(self):
        return str(self.name)
    
    
    
class Comment(models.Model):
    staff = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(null=True, blank=True)
    create_on = models.DateTimeField(auto_now_add=True)
    event_comment = models.ForeignKey(Event, related_name="comments", on_delete=models.CASCADE )

    def __str__(self):
        return str(self.staff)

    

events/forms.py
from django import forms
from bootstrap_modal_forms.forms import BSModalForm, BSModalModelForm
from events.models import Event, Comment

class EventForm(BSModalModelForm):
    class Meta:
        model = Event
        exclude = ('author',)
        fields = '__all__'
        widgets = {
            'status': forms.Select(attrs={'class': 'form-control selectpicker', 'data-style': 'btn btn-rose btn-sm', 'placeholder': 'Trạng Thái Sự Kiện'}),
            'status_atm': forms.Select(attrs={'class': 'form-control selectpicker', 'data-style': 'btn btn-rose btn-sm', 'placeholder': 'Trạng Thái ATM'}),
            'priority': forms.Select(attrs={'class': 'form-control selectpicker', 'data-style': 'btn btn-rose btn-sm', 'placeholder': 'Độ Ưu Tiên'}),
            'author': forms.Select(attrs={'class': 'form-control selectpicker', 'data-style': 'btn btn-rose btn-sm', 'placeholder': 'Người Tạo'}),
            'supervisor_note': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ghi nhận các thông tin ban đầu'}),
            'report24h': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'replace_components': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'end_funds': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'to_funds': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'date_complete': forms.DateTimeInput(format='%m/%d/%Y', attrs={'class':'form-control datetimepicker', 'placeholder': 'Ngày Hoàn Thành'}),
        }

class EventUpdateForm(BSModalModelForm):
    class Meta:
        model = Event
        exclude = ('author', 'name', 'status', 'supervisor_note','date_post' )
        fields = '__all__'
        widgets = {
            'status': forms.Select(attrs={'class': 'form-control selectpicker', 'data-style': 'btn btn-rose btn-sm', 'placeholder': 'Trạng Thái Sự Kiện'}),
            'status_atm': forms.Select(attrs={'class': 'form-control selectpicker', 'data-style': 'btn btn-rose btn-sm', 'placeholder': 'Trạng Thái ATM'}),
            'priority': forms.Select(attrs={'class': 'form-control selectpicker', 'data-style': 'btn btn-rose btn-sm', 'placeholder': 'Độ Ưu Tiên'}),
            'author': forms.Select(attrs={'class': 'form-control selectpicker', 'data-style': 'btn btn-rose btn-sm', 'placeholder': 'Người Tạo'}),
            'report24h': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'replace_components': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'end_funds': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'to_funds': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'date_complete': forms.DateTimeInput(format='%m/%d/%Y %H:%M', attrs={'class':'form-control datetimepicker', 'placeholder': 'Ngày Hoàn Thành'}),
            #'date_post': forms.DateTimeInput(format='%m/%d/%Y', attrs={'class':'form-control datetimepicker', 'placeholder': 'Ngày Post'}),
            'date_close': forms.DateTimeInput(format='%m/%d/%Y %H:%M', attrs={'class':'form-control ', 'placeholder': 'Ngày Kết Thúc', 'value': ''}),
        }
    
    
        
class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label = "",
        required=False,
        widget = forms.Textarea(attrs={'class': 'form-control', 'rows': '1'})
    )
    class Meta:
        model = Comment
        fields = ['content']
        

events/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages

from bootstrap_modal_forms.generic import (
    BSModalCreateView,
    BSModalDeleteView,
    BSModalFormView,
    BSModalReadView,
    BSModalUpdateView,
)

from events.models import Event, Error, Comment
from events.forms import EventForm, CommentForm, EventUpdateForm

# Create your views here.
@method_decorator(login_required, name='dispatch')
class Index(generic.ListView):
    model = Event
    context_object_name = 'events'
    template_name = 'event_home.html'   

@method_decorator(login_required, name='dispatch')
class EventCreateView(BSModalCreateView):
    template_name = 'event_create.html'
    form_class = EventForm
    success_message = 'Thành công: Một sự kiện đã được tạo!'
    success_url = reverse_lazy('event-home')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class EventUpdateView(BSModalUpdateView):
    model = Event
    template_name = 'event_update.html'
    form_class = EventUpdateForm
    success_message = 'Thành công: Sự kiện đã được cập nhật!'
    success_url = reverse_lazy('event-home')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        event_comment = Comment.objects.filter(event_comment=self.get_object()).order_by('-create_on')
        context['comments'] = event_comment
        if self.request.user.is_authenticated:
            context['comment_form'] = CommentForm(instance=self.request.user)
        return context
    
    def post(self, request, *args, **kwargs):
        new_comment = Comment(content=request.POST.get('content'), staff=self.request.user, event_comment=self.get_object())
        if new_comment.content:
            new_comment.save()
        return super(EventUpdateView, self).post(request, **kwargs)

    def form_valid(self, form):
        if form.instance.date_close:
            form.instance.status = 'close'
        elif form.instance.date_complete:
            form.instance.status = 'complete'
        else:
            form.instance.status = 'process'
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class EventDeleteView(BSModalDeleteView):
    model = Event
    template_name = 'event_delete.html'
    success_message = 'Thành công: Sự kiện đã được xóa hoàn toàn!'
    success_url = reverse_lazy('event-home')


events/templates/event_create.html
<form method="post" action="">
    {% csrf_token %}
    {{ form.media.js }}
    <div class="modal-header">
        <h5 class="modal-title">TẠO THÔNG TIN SỰ KIỆN ATM/CDM</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-sm-8">
                <div class="card">
                    <div class="card-header card-header-rose card-header-icon">
                        <div class="card-icon">
                        <i class="material-icons">contacts</i>
                        </div>
                        <h4 class="card-title">Thông tin</h4>
                    </div>
                    <div class="card-body ">
                        <div class="row">
                            <label class="col-md-3 col-form-label text-info">Tên ATM</label>
                            <div class="col-md-9">
                                <div class="form-group has-default">
                                    {{ form.name }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-md-3 col-form-label text-info">Tên Sự Kiện</label>
                            <div class="col-md-9">
                                <div class="form-group has-default">
                                    {{ form.error }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <label class="col-md-3 col-form-label text-info">Ghi Chú</label>
                            <div class="col-md-9">
                                <div class="form-group has-default">
                                    {{ form.supervisor_note }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-header card-header-rose card-header-icon">
                        <div class="card-icon">
                        <i class="material-icons">contacts</i>
                        </div>
                        <h4 class="card-title">Tùy Chọn</h4>
                    </div>
                    <div class="card-body ">                        
                        <div class="input-group">
                            {{ form.status_atm }}
                        </div>
                        <div class="input-group">
                            {{ form.status }}
                        </div>
                        <div class="input-group">
                            {{ form.priority }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save changes</button>
        <button type="submit" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
</form>



events/templates/event_delete.html
<form method="post" action="">
    {% csrf_token %}
    <div class="modal-body">
        <div class="info text-center">
            <div class="icon icon-danger ">
                <i class="material-icons">delete_forever</i>
            </div>
            <h2 class="info-title text-danger">BẠN CÓ CHẮC CHẮN MUỐN XOÁ?</h2>
            <p>Xoá toàn bộ thông tin về điểm <span class="text-primary">{{ event.name }}</span>!</p>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-danger">Xoá</button>
        <button type="submit" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
    </div>

</form>

events/templates/event_home.html
{% extends 'layouts/base.html' %}

{% block title %}
    Sự Kiện ATM/CDM
{% endblock title %}

{% block stylesheets %}
<style>
  .title-atms {
    font-size: 20px;
    font-weight: 700;
  }

 
  .event-font {
    font-size: 13px;
  }

  .overflow {
    #position: relative;
    width: auto;
    height: 390px;
    overflow: auto;
  }

  .select2-selection__rendered {
    font-size: 14px;
  }
  
  .alert-atm {
      display: inline-block;
      margin: 15px auto;
      position: fixed;
      transition: all 0.5s ease-in-out 0s;
      z-index: 1031;
      top: 20px;
      right: 20px;
  }
</style>
{% endblock stylesheets %}

{% block content %}    
  <div>
    {% if messages %}
      {% for message in messages %}
        <div class="col-11 col-md-4 alert alert-success alert-with-icon alert-atm" data-notify="container">
          <i class="material-icons" data-notify="icon">notifications</i>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <i class="material-icons">close</i>
          </button>
          <span data-notify="icon" class="now-ui-icons ui-1_bell-53"></span>
          <span data-notify="message">{{ message }}</span>
        </div>
      {% endfor %}            
    {% endif %}
  </div>
  <div class="modal fade" id="create-modal"  role="dialog" aria-hidden="true" >
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
      </div>
    </div>
  </div>

  <div class="modal fade" id="modal" role="dialog" aria-hidden="true">
    <div class=" modal-dialog modal-lg" role="document" >
      <div class="modal-content"></div>
    </div>
  </div>
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-primary card-header-icon">
                <div class="card-icon">
                    <i class="material-icons">assignment</i>
                </div>
                <h4 class="card-title">SỰ KIỆN ATM TẠM NGƯNG HOẠT ĐỘNG</h4>
            </div>
            <div class="card-body">
              <div class="toolbar">
                  <button id="atm-create" class="bs-modal btn btn-primary" type="button" name="button" data-form-url="{% url 'event-create' %}">
                      <i class="material-icons">add_box</i> Tạo Sự Kiện
                  </button>
              </div>
              <div class="material-datatables">
                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                  <thead>                                        
                    <tr>
                      <th>#</th>
                      <th style="width: 20%">Tên ATM</th>                         
                      <th style="width: 25%">Sự Kiện</th>
                      <th style="width: 10%">Phát Hiện</th>
                      <th style="width: 30%">Xử Lý</th>   
                      <th style="width: 10%">Status</th>                  
                      <th style="width: 5%" class="text-right disabled-sorting">Action</th>
                    </tr>
                  </thead>
                    <tfoot>
                      <tr>
                        <th>STT</th>
                        <th>Tên ATM</th>                         
                        <th>Sự Kiện</th>
                        <th>Phát Hiện</th>
                        <th>Xử Lý</th>
                        <th>Trạng Thái</th>
                        <th class="text-right">Action</th>
                      </tr>
                    </tfoot>
                    <tbody>
                      {% for event in events %}
                        <tr>
                            <td></td>
                            <td>
                              <a href="javascript:;" class="bs-modal" data-form-url="{% url 'event-update' event.pk %}">
                                {{ event.name }}
                              </a>
                            </td>  
                            <td>
                                {% if event.status_atm == 'out_services' %}
                                    <span class="badge badge-warning stats">OUT</span>
                                {% elif event.status_atm == 'in_services' %}
                                    <span class="badge badge-info stats">INS</span>
                                {% else %}
                                    <span class="badge badge-danger">OFF</span>
                                {% endif %}
                                {{ event.error }}
                                <br>
                                {% if event.supervisor_note %}
                                  <span class="small text-info">{{ event.supervisor_note }}</span>
                                {% endif %}
                            </td>
                            <td>{{ event.date_create|date:'m/d/Y H:i' }}</td>
                            <td>
                              {% if event.comments.all %}
                                {% for comment in event.comments.all %}
                                  {% if forloop.last %}
                                    {{ comment.content}}
                                  {% endif %}
                                {% endfor %}
                              {% else %}
                                {{ event.supervisor_note }}
                              {% endif %}
                              
                              <br>
                              {% if event.report24h %}
                                <span class="badge badge-default" >BC 24h</span>
                              {% endif %}
                              {% if event.replace_components %}
                                <span class="badge badge-default" >Thay LKTB</span>
                              {% endif %}
                              {% if event.end_funds %}
                                <span class="badge badge-default" >Cất Tiền</span>
                              {% endif %}
                              {% if event.to_funds %}
                                <span class="badge badge-default" >Tiếp Quỹ</span>
                              {% endif %}
                              {% if event.handling_staff_event %}
                                
                                <span class="small text-info">NVXL: {{ event.handling_staff_event }}</span>
                              {% endif %}
                              
                            </td>
                            <td class="text-center">
                              {% if event.status == 'new' %}
                                  <span class="badge badge-primary">
                              {% elif event.status == 'process' %}
                                  <span class="badge badge-danger">
                              {% elif event.status == 'complete' %}
                                  <span class="badge badge-success">
                              {% else %}
                                  <span class="badge badge-default">
                              {% endif %}
                              {{ event.get_status_display }}</span>
                            </td>
                            <td class="text-right ">
                              <div class="btn-group">
                                <button type="button" class="bs-modal btn btn-sm btn-info" data-form-url="{% url 'event-update' event.pk %}"><i class="material-icons">create</i></button>
                                <button type="button" class="btn btn-sm btn-warning dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <div class="dropdown-menu">
                                  <a class="dropdown-item" href="javascript:;">Xem Thông Tin</a>
                                  <div class="dropdown-divider"></div>
                                  <a class="bs-modal dropdown-item" data-form-url="{% url 'event-delete' event.pk %}" href="javascript:;">Xoá Sự Kiện</a>
                                </div>
                              </div>
                            </td>
                        </tr>
                      {% empty %}
                        <tr>
                          <td colspan="4">Chưa có sự kiện! <a href="#">Tạo sự kiện ATM ngay!</a>.</td>
                        </tr>
                      {% endfor %}
                    </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>        
    
{% endblock content %}

{% block javascripts %}
<script>
  $(document).ready(function() {
    var table = $('#datatables').DataTable({
      //scrollCollapse: true,
      paging: true,
      //scrollY: '350px',
      "order": [[3,"desc"]],
      "pagingType": "full_numbers",
      "lengthMenu": [
      [10, 25, 50, -1],
      [10, 25, 50, "All"]
      ],
      responsive: true,
      language: {
        search: "TÌM KIẾM: ",
        searchPlaceholder: "Thông tin sự kiện...",
      }
    });
    
    table.on( 'order.dt search.dt', function () {
      table.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
        cell.innerHTML = i+1;
      });
    }).draw();
  });

  //Hàm tự động render modal cho class bs-modal
  $(".bs-modal").each(function () {
      $(this).modalForm({formURL: $(this).data("form-url")});
  });  
  
  //Ẩn thông báo khi tạo mới, cập nhật hoặc xoá
  $(".alert").fadeTo(5000, 500).slideUp(500, function () {
      $(".alert").slideUp(500);
  
  }); 

  
  $('#modal').on('shown.bs.modal', function () {
    //Chèn select2 vào
    $('#id_name').select2({
      width: '100%',
      placeholder: "Chọn Tên ATM/CDM",
    });
    $('#id_error').select2({
      width: '100%',
      placeholder: "Chọn Sự Kiện Phát Sinh",
    });
    $('#id_handling_staff_event').select2({
      width: '100%',
      placeholder: "Chọn Nhân Viên Xử Lý",
    });

    //Chèn Selectpicker vào
    $('.selectpicker').selectpicker();

    //Chèn datepicker vào (Nếu muốn chèn thêm time: datetimepicker )
    md.initFormExtendedDatetimepickers();

    setTimeout(function (){
      $('#id_name, #id_content').focus();
    }, 200);

    atm_plug.initMaterialWizard();
    
    //Tự động mở drop khi nhấn tab
    $(document).on('focus', '.select2.select2-container', function (e) {
      var isOriginalEvent = e.originalEvent // don't re-open on closing focus event
      var isSingleSelect = $(this).find(".select2-selection--single").length > 0 // multi-select will pass focus to input

      if (isOriginalEvent && isSingleSelect) {
          $(this).siblings('select:enabled').select2('open');
      } 
    }); 
    //Xóa class 'ps' div main-panel
    $('.main-panel').removeClass('ps');  

    //Chèn ngày giờ vào date_close khi nhấn nút
    $('#bt_date_close').click(function(){
      var time = moment().format('MM/DD/YYYY HH:mm') 
      $('#id_date_close').val(time);  
    });
    $('#bt_date_close_restore').click(function(){
      var time = "" 
      $('#id_date_close').val(time);  
    });
  });

  $('#modal').on('hidden.bs.modal', function() {
    $('.main-panel').addClass('ps');
  });

  $(window).scroll(function() {
  sessionStorage.scrollTop = $(this).scrollTop();
});

$(document).ready(function() {
  if (sessionStorage.scrollTop != "undefined") {
    $(window).scrollTop(sessionStorage.scrollTop);
  }
});

</script>  

{% endblock javascripts %}

